name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]  # Run on push to either main or master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is important for the deploy action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install  # Using install instead of ci for more reliability

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: ${{ steps.pages.outputs.cname }}
          enable_jekyll: false
          force_orphan: true  # Force create single-commit gh-pages branch
